# Generated by Django 5.1.11 on 2025-07-22 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speedmeasurement',
            name='measurement_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
